### ISSUE TITLE
Sphinx Plugin: PDB2PQR

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/APBS_Sphinx#11]
I'm not exactly sure what this was _supposed_ to be.  But since the PDB2PQR functionality will be broken up into many different plugins, I'm going to hijack this to mean: "stuff PDB2PQR into Sphinx".  Why would we do that?  We'll, it's a nice intermediate step to getting a fully broken out, plugin only implementation.

**Comment by keith923** [comment]
This is generally working now.  A user can specify options either by passing them from the command line invocation (with an appropriate pipeline file) or, as it is now, by specifying them in a json file.  The only thing I'm really unhappy with is that the pdb file should be specified on the command line, and options in a file.  I'll create an issue to deal with that...
