### ISSUE TITLE
Sphinx Databus: extend to MDB

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/APBS_Sphinx#2]

**Comment by lizutah** [comment]
@sobolevnrm - can you remind us what MDB stands for?  :-)

**Comment by sobolevnrm** [comment]
"*M*ultiple *D*ebye-Hückel [sphere] *B*oundary [condition]"

I think it's called "MDH" in the documentation, though.

**Comment by keith923** [comment]
I'm not sure that MDB == MDH in this context -- it just doesn't seem to make sense.  At least not to me.  Hrm.

**Comment by sobolevnrm** [comment]
OK, then I need more context...

**Comment by lizutah** [comment]
This is related to #1.

**Comment by keith923** [comment]
I'm just closing this as the original meaning of "MDB" has been lost, and if it's important, and not already completed, we'll notice and create a new issue.
