### ISSUE TITLE
Update Plugins to accept lists of data

### ISSUE THREAD

**Issue by keith923** [Electrostatics/APBS_Sphinx#25]
Some of the plugins (at least Geoflow, and likely others) are written with the assumption that they are orly receiving one datum at a time from the Data Bus.  This is incorrect now, and needs fixing.

**Comment by keith923** [comment]
Maria, this would be perfect for you.  Let me know if you need clarification or guidance, and we'll talk.

**Comment by mtartakovsky** [comment]
@keith923 Does this mean one file at a time, or one line at a time?

**Comment by keith923** [comment]
I'm not sure what you mean wrt files.

Take a look at line 84 in the ParseXYZR plugin, and you can see where it's using a for loop to iterate over an array of "stuff" that's passed to the plugin.  This is the right way.  It's receiving multiple data in a single call.  The Geoflow plugin does not do this.  It instead assumes that it's getting all of the data that it needs in one shot.

**Comment by mtartakovsky** [comment]
@keith923 I made a small change to the Geoflow plugin

**Comment by keith923** [comment]
Done as well.  Fantastic!
