### ISSUE TITLE
Plugin loading should be smarter

### ISSUE THREAD

**Issue by keith923** [Electrostatics/APBS_Sphinx#26]
It's a good idea that plugins are automatically loaded, but if a directory in the "plugins" dir is not a plugin, Sphinx pukes.

**Comment by keith923** [comment]
I think that there are two things here that would make plugin loading better:
1. check that there is actually a "plugin.py" file inside the directory in the "plugins" dir before attempting to dynamically import the module
2. see if there is some clever way to disentangle the name of the name of the plugin module (the directory name) from the name of the plugin class

**Comment by sobolevnrm** [comment]
![Yay](http://i.giphy.com/MTclfCr4tVgis.gif)
