### ISSUE TITLE
Plugin that fetches a PDB file

### ISSUE THREAD

**Issue by keith923** [Electrostatics/APBS_Sphinx#34]
We can easily write a pipeline file that takes a PDB file argument, and if the file exists, use ReadFile to read it, and otherwise, uses a different plugin to fetch the PDB file from RCSB PDB.

Maria, I think that this would be good for you to work on...

**Comment by mtartakovsky** [comment]
Hey Keith, just wanted to confirm for Plugin that fetches a PDB file #34 I should write the plugin that gets the pub file from RCSB PDB not the pipeline file ?

**Comment by keith923** [comment]
I think that I was pretty unclear about what I'm looking for.  I'd like a plugin that fetches a PDB file from RCSB.  Once that's done, we can consider what it would take to create a pipeline file as described above.

**Comment by keith923** [comment]
Maria finished this one.
