### ISSUE TITLE
Update sources to PEP 492 syntax

### ISSUE THREAD

**Issue by keith923** [Electrostatics/APBS_Sphinx#36]
We should switch to the [new syntax](https://www.python.org/dev/peps/pep-0492/).

**Comment by keith923** [comment]
Rather than forcing you to read that entire PEP, which I still haven't, I can tell you that this should boil down to replacing `@coroutine` or `@asyncio.coroutine` with `async def` and `yield from` with `await`.

**Comment by keith923** [comment]
We'll need to make sure that we are bootstrapping Python 3.5, as that's the minimum version for this syntax.

**Comment by keith923** [comment]
Also, with the new syntax, it's unnecessary to import asyncio if you are just using coroutine.

**Comment by mtartakovsky** [comment]
@keith923 should I make these changes to the other plugins?

**Comment by keith923** [comment]
Complete!

**Comment by keith923** [comment]
Whoops -- spoke too soon.  Something is wrong with this and the CI is complaining.  I should have run the unit testes before committing.  Sigh.

**Comment by keith923** [comment]
I've stopped flagellating myself.  Turns out that Travis is not using Python 3.5.  Hopefully that can be fixed.

**Comment by keith923** [comment]
Simple update to travis config file.
