### ISSUE TITLE
Add preprocessor to pipeline files

### ISSUE THREAD

**Issue by keith923** [Electrostatics/APBS_Sphinx#37]
I think that just using Python for our pipeline files is less than optimal, although I consider it a generally good idea (I've come around, I think).  So, I'd like to introduce a preprocessor.  Something that could take a slightly simpler syntax and transform it to proper Python.  For example, rather than this:

``` python
read_file(params['input_file']).process_data().write_file(params['output_file'])
```

something like this:

```
read_file(#input_file) -> process_data -> write_file(#output_file)
```

which would become:

``` python
read_file(params['input_file']).process_data().write_file(params['output_file'])
```

Having a preprocessor would also enable something like this for remote jobs:

```
read_file(#input_file) -> process_data@remote.server.com -> write_file(#output_file)
```

which may become:

``` python
read_file(params['input_file']).process_data(remote='remote.server.com').write_file(params['output_file'])
```

Of course Python could still exist in a pipeline:

```
in = read_file(#input_file)
if (#remote):
    processed = in -> process_data@remote.server.com
else:
    processed = in -> process_data

processed -> write_file(#output_file)
```

translates to:

``` python
in = read_file(params['input_file'])
if (params['remote']):
    processed = in.process_data(remote=params['remote'])
else:
    processed = in.process_data()

processed.write_file(params['output_file'])
```

The preprocessor should be easily extensible for new syntax.

**Comment by sobolevnrm** [comment]
Hi Keith --

This is an interesting idea but I think we should have more discussion
about the intended audience for the pipeline.  Most of our users will not
be authoring pipeline documents but rather executing pipelines created by
developers.  Given this, is additional syntax/parsing worth the extra
effort?

Thanks,

Nathan

**Comment by keith923** [comment]
@sobolevnrm you are correct.  When I had this idea I wasn't thinking about our intended audience.  I'll move this to wontfix.  We can always resurrect it if necessary.  Thanks!
