### ISSUE TITLE
Add debug flag to apbs.py

### ISSUE THREAD

**Issue by keith923** [Electrostatics/APBS_Sphinx#38]
Per the Python [documentation](https://docs.python.org/3/library/asyncio.html), we should have a means to enable all of the [asyncio debugging](https://docs.python.org/3/library/asyncio-dev.html#asyncio-debug-mode) during development in order to identify common errors.

I suggest that we add a debug flag, e.g., `--debug`, in apbs.py.

**Comment by keith923** [comment]
We covered the first two bullets on the debugging page:
- Enable the asyncio debug mode globally by setting the environment variable PYTHONASYNCIODEBUG to 1, or by calling BaseEventLoop.set_debug().
- Set the log level of the asyncio logger to logging.DEBUG. For example, call logging.basicConfig(level=logging.DEBUG) at startup.

The third one, "Configure the warnings module to display ResourceWarning warnings", requires some research to figure out how to do that.

**Comment by keith923** [comment]
I think that third bullet can be accomplished by calling [warnings.filterwarnings](https://docs.python.org/3/library/warnings.html#warnings.filterwarnings).  See [warnings filter](https://docs.python.org/3/library/warnings.html#warning-filter) for more information.

**Comment by mtartakovsky** [comment]
@keith923 I added warnings.simplefilter('default', ResourceWarning). Not sure if default is the setting we wanted to use.

**Comment by keith923** [comment]
Perfect @mtartakovsky!  Thanks!
