### ISSUE TITLE
Bootstrap Python library installation

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/APBS_Sphinx#6]
Create a script that automatically installs all the necessary libraries to develop in Python.

**Comment by kmonson** [comment]
This should also create a virtual environment. There is a good example of a bootstrap script we can use as a starting point here: https://github.com/VOLTTRON/openeis/blob/2.x/bootstrap.py

**Comment by keith923** [comment]
There is now a bootstrap file that creates a virtual environment and installs the required Python libs.  Usage is described in the README.md file.  Dependent libs are stored in packages.txt.  There will likely need to be changes in the future (command line args for customization, etc.) but for now it's good enough.
